const seedPlaces=[
 {id:1,type:'place',name:'清水寺',city:'京都市 · 日本',country:'日本',date:'2024-04-18',lat:34.9949,lng:135.7850,guide:'清晨八点前到，人少光线也好。'},
 {id:2,type:'place',name:'奈良公园',city:'奈良市 · 日本',country:'日本',date:'2024-04-16',lat:34.6851,lng:135.8430,guide:'东大寺和春日大社建议分开半天。'},
 {id:3,type:'food',name:'% Arabica Kyoto',city:'东山区 · 日本',country:'日本',date:'2024-04-18',lat:34.9968,lng:135.7785,guide:'八坂塔旁边的咖啡窗口。'},
 {id:4,type:'place',name:'姬路城',city:'姬路市 · 日本',country:'日本',date:'2024-04-14',lat:34.8394,lng:134.6939,guide:'樱花季建议预约入场。'},
 {id:5,type:'food',name:'京都胜牛',city:'京都市 · 日本',country:'日本',date:'2024-04-17',lat:35.0035,lng:135.7681,guide:'排队时间较长，错峰前往。'},
 {id:6,type:'place',name:'白川乡合掌村',city:'岐阜县 · 日本',country:'日本',date:'2023-11-08',lat:36.2575,lng:136.9060,guide:'巴士班次少，提前查好时间。'},
 {id:7,type:'place',name:'台北 101',city:'信义区 · 中国台湾',country:'中国台湾',date:'2023-10-22',lat:25.0340,lng:121.5645,guide:'日落前登顶可以看到城市灯亮起来。'},
 {id:8,type:'food',name:'阜杭豆浆',city:'中正区 · 中国台湾',country:'中国台湾',date:'2023-10-21',lat:25.0447,lng:121.5254,guide:'早起排队，蛋饼和厚烧饼必点。'},
 {id:9,type:'place',name:'乌尤尼盐沼',city:'波托西省 · 玻利维亚',country:'玻利维亚',date:'2022-08-06',lat:-20.1338,lng:-67.4891,guide:'旱季的星空和镜面都值得。'}
];
let places=JSON.parse(localStorage.getItem('travel_places')||'null')||seedPlaces;let map,markers=[],route;
const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function icon(type){return L.divIcon({className:'custom-pin',html:`<span style="display:block;width:14px;height:14px;border-radius:50%;background:${type==='food'?'#e17c45':'#1d6a5b'};border:3px solid white;box-shadow:0 2px 8px rgba(20,50,40,.25)"></span>`,iconSize:[14,14],iconAnchor:[7,7]})}
function renderList(){const q=$('#searchInput').value.toLowerCase();const shown=places.filter(p=>(p.status||'published')==='published'&&[p.name,p.city,p.country,p.guide].some(x=>(x||'').toLowerCase().includes(q)));$('#visibleCount').textContent=String(shown.length).padStart(2,'0');$('#placeCount').textContent=String(places.filter(p=>p.type==='place').length).padStart(2,'0');$('#foodCount').textContent=String(places.filter(p=>p.type==='food').length).padStart(2,'0');$('#placeList').innerHTML=shown.sort((a,b)=>b.date.localeCompare(a.date)).map(p=>`<article class="place-card" data-id="${p.id}"><div class="place-top"><i class="place-dot ${p.type}"></i><div><h3>${esc(p.name)}</h3><p>${esc(p.city)}</p></div></div><div class="place-meta"><span>${p.date.replaceAll('-',' / ')}</span><b>${p.type==='food'?'美食':'景点'}　›</b></div></article>`).join('');document.querySelectorAll('.place-card').forEach(el=>el.onclick=()=>focusPlace(+el.dataset.id));renderMarkers(shown)}
function renderMarkers(shown){markers.forEach(m=>m.remove());markers=[];if(route)route.remove();shown.forEach(p=>{const m=L.marker([p.lat,p.lng],{icon:icon(p.type)}).addTo(map).bindPopup(`<div class="popup-title">${esc(p.name)}</div><div class="popup-meta">${esc(p.city)} · ${p.date}</div>`);m.on('click',()=>document.querySelector(`[data-id="${p.id}"]`)?.classList.add('selected'));markers.push(m)});if($('#lineToggle').classList.contains('on')&&shown.length>1){const sorted=[...shown].sort((a,b)=>a.date.localeCompare(b.date));route=L.polyline(sorted.map(p=>[p.lat,p.lng]),{color:'#4b9582',weight:2,dashArray:'5 7',opacity:.8}).addTo(map)}}
function focusPlace(id){const p=places.find(x=>x.id===id);if(!p)return;map.flyTo([p.lat,p.lng],Math.max(map.getZoom(),10),{duration:.6});const i=places.filter(x=>(x.status||'published')==='published').findIndex(x=>x.id===id);if(markers[i])markers[i].openPopup();document.querySelectorAll('.place-card').forEach(x=>x.classList.toggle('selected',+x.dataset.id===id))}
function initMap(){map=L.map('map',{zoomControl:false,dragging:true,touchZoom:true,scrollWheelZoom:true,doubleClickZoom:true,boxZoom:true,keyboard:true}).setView([30,112],3);map.dragging.enable();map.touchZoom.enable();L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);renderList();$('#zoomIn').onclick=()=>map.zoomIn();$('#zoomOut').onclick=()=>map.zoomOut();$('#locateBtn').onclick=()=>map.setView([30,112],3)}
function openModal(type='place'){ $('#modalTypeLabel').textContent=type==='food'?'美食':'景点';$('#modalTitle').textContent=type==='food'?'记录一家美食':'记录一处景点';$('#modalBackdrop').classList.remove('hidden');$('#entryForm').dataset.type=type;setTimeout(()=>$('#entryForm input').focus(),80)}
function closeModal(){$('#modalBackdrop').classList.add('hidden');$('#entryForm').reset()}
function showToast(){const t=$('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function renderManage(){const rows=places.map(p=>`<div class="table-row"><strong>${esc(p.name)}</strong><span>${esc(p.city)}</span><span><i class="tag ${p.type==='food'?'food':''}">${p.type==='food'?'美食':'景点'}</i></span><span><i class="tag ${p.status==='draft'?'draft':''}">${p.status==='draft'?'草稿':'已发布'}</i></span><span class="row-actions">···</span></div>`).join('');$('#manageTable').innerHTML='<div class="table-row head"><span>名称</span><span>地区</span><span>类型</span><span>状态</span><span></span></div>'+rows}
document.addEventListener('DOMContentLoaded',()=>{initMap();renderManage();$('#searchInput').oninput=renderList;$('#lineToggle').onclick=()=>{$('#lineToggle').classList.toggle('on');renderList()};$('#newPlaceBtn').onclick=()=>openModal('place');$('#newFoodBtn').onclick=()=>openModal('food');$('#manageNewBtn').onclick=()=>openModal('place');$('#modalClose').onclick=closeModal;$('#cancelBtn').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#entryForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const p={id:Date.now(),type:e.target.dataset.type,name:f.get('name'),country:f.get('country'),city:f.get('city'),address:f.get('address'),date:f.get('date'),lat:+f.get('lat')||35,lng:+f.get('lng')||135,guide:f.get('guide'),status:f.get('status')};places.push(p);localStorage.setItem('travel_places',JSON.stringify(places));closeModal();renderList();renderManage();showToast()};document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));n.classList.add('active');const isMap=n.dataset.view==='map';$('#mapView').classList.toggle('hidden',!isMap);$('#manageView').classList.toggle('hidden',isMap);if(isMap)setTimeout(()=>map.invalidateSize(),50);else renderManage()});$('#manageBtn').onclick=()=>document.querySelector('[data-view="manage"]').click()});
let authRegister=false;
function openAuth(){ $('#authBackdrop').classList.remove('hidden'); $('#authError').textContent=''; $('#authForm').reset(); }
async function submitAuth(e){e.preventDefault();const f=new FormData(e.target);const endpoint=authRegister?'/api/auth/register':'/api/auth/login';try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({username:f.get('username'),password:f.get('password')})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'请求失败');localStorage.setItem('travel_user',JSON.stringify(data));$('#accountName').textContent=data.username||f.get('username');$('#authBackdrop').classList.add('hidden');showToast()}catch(err){$('#authError').textContent=err.message+'（后端未启动时可继续使用本地原型）'}}
document.addEventListener('DOMContentLoaded',()=>{$('#accountBtn').onclick=openAuth;$('#authClose').onclick=()=>$('#authBackdrop').classList.add('hidden');$('#authBackdrop').onclick=e=>{if(e.target.id==='authBackdrop')e.currentTarget.classList.add('hidden')};$('#authForm').onsubmit=submitAuth;$('#authSwitch').onclick=()=>{authRegister=!authRegister;$('#authTitle').textContent=authRegister?'注册足迹':'登录足迹';$('#authSubmit').firstChild.textContent=authRegister?'注册 ':'登录 ';$('#authSwitch').textContent=authRegister?'已有账号，去登录':'注册新账号'};const u=JSON.parse(localStorage.getItem('travel_user')||'null');if(u?.username)$('#accountName').textContent=u.username});
