CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE places (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  name VARCHAR(120) NOT NULL,
  country VARCHAR(80), province VARCHAR(80), city VARCHAR(80), address VARCHAR(255),
  longitude DECIMAL(10,7) NOT NULL, latitude DECIMAL(10,7) NOT NULL,
  visit_date DATE NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', guide_content TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_places_user FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX idx_places_geo (latitude, longitude), INDEX idx_places_user_date (user_id, visit_date)
);

CREATE TABLE foods (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, place_id BIGINT NULL,
  name VARCHAR(120) NOT NULL, address VARCHAR(255) NOT NULL, longitude DECIMAL(10,7) NOT NULL, latitude DECIMAL(10,7) NOT NULL,
  price DECIMAL(10,2), rating DECIMAL(2,1), opening_hours VARCHAR(120), link VARCHAR(500), notes TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'draft', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_foods_user FOREIGN KEY (user_id) REFERENCES users(id), CONSTRAINT fk_foods_place FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE SET NULL,
  INDEX idx_foods_geo (latitude, longitude)
);
